R0Wi-DEV/workflow_ocr

- README.md
Updated documentation and added notice that Imagick requires Ghostscript to properly read PDF files. Therefore, added Ghostscript as used component to the library and component overview in the documentation.
> Added doc for required component Ghostscript

- README.md
Fixed the name of the local folder created by the Git clone command such that the following commands in the documentation succeed.
> Fixed wrong git clone command in doc

- Makefile
The following two targets
- lint
- lint-fix
are added to the Makefile to execute a source code check (lint) and to fix detected source code issues (lint-fix).
> Added Lint targets to Makefile

- .github/workflows/build.yml
- .gitignore
- README.md
Repo name changed from `nextcloud_workflow_ocr` to `workflow_ocr` to be consistent with NC defaults.
> Update repo name to be consistent with NC defaults

- .github/workflows/phpunit.yml
- lib/Operation.php
- tests/Unit/OperationTest.php
* Use IRuleMatcher getFlows
Filter unwanted events for users
by invoking ruleMatchers getFlows method.
This will apply various checks and only
return a value if all checks passed.
Fixes #60
* "Fix" CI with mariadb
Inspired by
https://github.com/nextcloud/spreed/commit/e8b1456f064b2e9d07aed01c87f25360addeb8d4
> Manual backport of 'Use IRuleMatcher getFlows (closes #60) (#61)' for NC 22

- .github/workflows/phpunit.yml
- lib/Operation.php
- tests/Unit/OperationTest.php
* Use IRuleMatcher getFlows
Filter unwanted events for users
by invoking ruleMatchers getFlows method.
This will apply various checks and only
return a value if all checks passed.
Fixes #60
* "Fix" CI with mariadb
Inspired by
https://github.com/nextcloud/spreed/commit/e8b1456f064b2e9d07aed01c87f25360addeb8d4
> Manual backport of 'Use IRuleMatcher getFlows (closes #60) (#61)' for NC 20

- .github/workflows/phpunit.yml
- lib/Operation.php
- tests/Unit/OperationTest.php
* Use IRuleMatcher getFlows
Filter unwanted events for users
by invoking ruleMatchers getFlows method.
This will apply various checks and only
return a value if all checks passed.
Fixes #60
* "Fix" CI with mariadb
Inspired by
https://github.com/nextcloud/spreed/commit/e8b1456f064b2e9d07aed01c87f25360addeb8d4
> Manual backport of 'Use IRuleMatcher getFlows (closes #60) (#61)' for NC 21

- .github/workflows/backport.yml
If commits from a pull request are backported to stable branches the backporting fails. This patch pins the backport Github action to an older working version, since the latest version (1.1.1) does not work properly.
This patch fixes #65.
> Pin automatic backport Github action in CI/CD chain to version 1.1.0

- README.md
- lib/BackgroundJobs/ProcessFileJob.php
- lib/OcrProcessors/OcrProcessorFactory.php
- lib/OcrProcessors/PdfOcrProcessor.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
- tests/Unit/OperationTest.php
With respect to the [`ocrmypdf`-docs](https://ocrmypdf.readthedocs.io/en/latest/advanced.html#return-code-policy) and the [reference server implementation](https://github.com/jbarlow83/OCRmyPDF/blob/313c9e7dc171351126ad6dac3d5b46cea27cc6f7/misc/webservice.py#L63) we should accept all OCR results where `ocrmypdf` command succeeds with exitcode 0.
> Accept results with ocrmypdf exit code 0

- .gitignore
- lib/OcrProcessors/PdfOcrProcessor.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
Signed-off-by: Robin Windey <ro.windey@gmail.com>
> Do not accept empty OCRmyPDF results #79

- .gitignore
- lib/OcrProcessors/PdfOcrProcessor.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
Backport 6b99bcb04b9536556396c1d154ae8ee43c7761b7 from #80
> [Backport stable23] Do not accept empty OCRmyPDF results #79

- package-lock.json
Backport 759c43fdc374f3385da3a5dc1d8bee8547011ef5 from #90
> [Backport stable22] Bump node-fetch from 2.6.6 to 2.6.7

- package-lock.json
Backport 759c43fdc374f3385da3a5dc1d8bee8547011ef5 from #90
> [Backport stable23] Bump node-fetch from 2.6.6 to 2.6.7

- lib/BackgroundJobs/ProcessFileJob.php
- lib/Operation.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
- tests/Unit/OperationTest.php
- tests/psalm-baseline.xml
* Read user id from filepath, don't use fileowner
* Use new \OCP\BackgroundJob\QueuedJob base class
* Closing #110
> Use uid from filepath

- lib/BackgroundJobs/ProcessFileJob.php
- lib/Operation.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
- tests/Unit/OperationTest.php
Backport https://github.com/R0Wi/workflow_ocr/commit/3b0f56a6c6d4e034a02771a539f64648aaf48b7d from https://github.com/R0Wi/workflow_ocr/pull/116
> [Backport stable23] Use uid from filepath (#116)

- README.md
- lib/OcrProcessors/PdfOcrProcessor.php
- src/components/WorkflowOcr.vue
- src/test/components/WorkflowOcr.spec.js
Backport 2469940df1a93cf4f9205136babdef4b8196f27f from #120
> [Backport stable23] Add chinese simplified

- README.md
- lib/OcrProcessors/OcrMyPdfBasedProcessor.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
> Implement --skip-text as default setting

- README.md
- lib/OcrProcessors/OcrMyPdfBasedProcessor.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
Backport e90c57a676bb96ea38830eb14ab56f0149e750e2 from #126
> [Backport stable23] Implement --skip-text as default setting

- .github/workflows/build.yml
- .github/workflows/build_release.yml
- .github/workflows/codecov.yml
- .github/workflows/lint-fix.yml
- .github/workflows/lint.yml
- .github/workflows/phpunit.yml
Update checkout action to v3 to remove warnings in Github actions
> [DEVOPS] Update checkout action to v3

- lib/BackgroundJobs/ProcessFileJob.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
Only create new file version if OCR result was not empty
Signed-off-by: Robin Windey <ro.windey@gmail.com>
> Implement #130

- lib/BackgroundJobs/ProcessFileJob.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
Backport 8cfba2c7463f54e45aa35bab0441cba56b8e84c0 from #160
> [Backport stable24] Implement #130

- lib/BackgroundJobs/ProcessFileJob.php
- lib/Exception/OcrProcessorNotFoundException.php
- lib/OcrProcessors/OcrMyPdfBasedProcessor.php
- lib/Operation.php
- tests/Integration/Notification/NotificationTest.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
- tests/Unit/OperationTest.php
Closing #112
**Testplan**
* Ensure that OCR processing for PDF and JPG files still works as before
* Create manual testcase where we upload a matching document but before triggering `cron.php` we rename the file. OCR process should still work afterwards.
**Artifact**
Install artifact for NC28: https://github.com/R0Wi-DEV/workflow_ocr/suites/15532932389/artifacts/886555625
> Process OCR files by file id

- lib/BackgroundJobs/ProcessFileJob.php
- lib/Exception/OcrProcessorNotFoundException.php
- lib/OcrProcessors/OcrMyPdfBasedProcessor.php
- lib/Operation.php
- tests/Integration/Notification/NotificationTest.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
- tests/Unit/OperationTest.php
Backport aa5e73d9646814cb59ccd48b1e83f2bacf46bbe3 from #225
> [Backport stable27] Process OCR files by file id

- lib/Migration/Version2702Date20230908170345.php
- lib/Notification/Notifier.php
- tests/Unit/Notification/NotifierTest.php
> Fix Notifications not being processed #221

- composer.json
- tests/Integration/Composer/AutoloaderTest.php
Backport ed26760218e6aa871e64c52662cbf001dd807bfc from #230
> [Backport stable27] fix: Allow dynamic autoloading for classes added during upgrade

- lib/BackgroundJobs/ProcessFileJob.php
- lib/Exception/OcrResultEmptyException.php
- lib/Migration/Version2404Date20220903071748.php
- lib/OcrProcessors/OcrMyPdfBasedProcessor.php
- lib/Service/IOcrService.php
- lib/Service/OcrService.php
- tests/Integration/Notification/NotificationTest.php
- tests/Unit/BackgroundJobs/ProcessFileJobTest.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
- tests/Unit/Service/OcrServiceTest.php
- tests/psalm-baseline.xml
* Fixes #232
* Move logic to OcrService
> Skip notifications when OCR mode is "skip file"

- package-lock.json
Backport 999be0ab74f9e15b23d11d2f320301e3540d3c55 from #245
> [Backport stable29] Build(deps-dev): Bump express from 4.18.2 to 4.19.2

- package-lock.json
Backport 999be0ab74f9e15b23d11d2f320301e3540d3c55 from #245
> [Backport stable28] Build(deps-dev): Bump express from 4.18.2 to 4.19.2

- lib/OcrProcessors/OcrMyPdfBasedProcessor.php
- tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
* Adjust ocrMyPdf command
* Ensure error code of ocrMyPdf command is returned
* Fixes #259
> Avoid pipe to get original error code

- lib/Service/OcrService.php
- tests/Unit/Service/OcrServiceTest.php
- tests/psalm-baseline.xml
> Make dependency to File Versions App optional
