R0Wi-DEV/workflow_ocr

README.md

Resized and aligned existing images in the documentation such that all images are centered and do not exceed the documentation's boundary box.

Formated images in doc

---

README.md

Added shell command wget to the documentation to download the current release into the Nextcloud app folder.

Added command to doc to download release correctly

---

.github/workflows/build.yml
appinfo/info.xml

Release 1.19.0

---

.github/workflows/backport.yml
.github/workflows/build.yml
.github/workflows/build_release.yml
.github/workflows/coverage.yml
.github/workflows/dependabot-approve.yml
.github/workflows/lint-fix.yml
.github/workflows/lint.yml
.github/workflows/phpunit.yml
.github/workflows/release-drafter.yml
.github/workflows/toc_generator.yml
README.md
appinfo/info.xml
composer.json
composer.lock
lib/BackgroundJobs/ProcessFileJob.php
lib/Operation.php
phpunit.integration.xml
phpunit.xml
tests/Integration/AppTest.php

This PR is for supporting NC21. The branch will be stabilized and then merged.

Support Nextcloud 21

---

.github/workflows/phpunit.yml
lib/Operation.php
tests/Unit/OperationTest.php

Filter unwanted events for users
by invoking ruleMatchers getFlows method.
This will apply various checks and only
return a value if all checks passed.
Fixes #60

Use IRuleMatcher getFlows (closes #60)

---

README.md
lib/BackgroundJobs/ProcessFileJob.php
lib/OcrProcessors/OcrProcessorFactory.php
lib/OcrProcessors/PdfOcrProcessor.php
tests/Unit/BackgroundJobs/ProcessFileJobTest.php
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
tests/Unit/OperationTest.php

Backport 2bac1874cec319a4e9e884576f4fb2b513ae7fa3 from #69

[Backport stable22] Accept results with ocrmypdf exit code 0

---

.gitignore
lib/OcrProcessors/PdfOcrProcessor.php
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php

Backport 6b99bcb04b9536556396c1d154ae8ee43c7761b7 from #80

[Backport stable22] Do not accept empty OCRmyPDF results #79

---

package-lock.json

Backport 0d1e619277d5b2dade13aaa5d0400ab853baf664 from #94

[Backport stable22] Bump url-parse from 1.5.3 to 1.5.7

---

package-lock.json

Backport 0d1e619277d5b2dade13aaa5d0400ab853baf664 from #94

[Backport stable23] Bump url-parse from 1.5.3 to 1.5.7

---

package-lock.json

Backport be1d8a235bbc1618d66931a5cb6cebf93e87b991 from #91

[Backport stable22] Bump follow-redirects from 1.14.5 to 1.14.8

---

package-lock.json

Backport be1d8a235bbc1618d66931a5cb6cebf93e87b991 from #91

[Backport stable23] Bump follow-redirects from 1.14.5 to 1.14.8

---

package-lock.json

Backport 9a86d7782ee733af480d832027d6bd4505f1ffc6 from #101

[Backport stable22] Bump prismjs from 1.25.0 to 1.27.0

---

package-lock.json

Backport 9a86d7782ee733af480d832027d6bd4505f1ffc6 from #101

[Backport stable23] Bump prismjs from 1.25.0 to 1.27.0

---

package-lock.json

Backport 5493f1453627013c18e3b17c51af154bea46c5f3 from #102

[Backport stable22] Bump url-parse from 1.5.7 to 1.5.10

---

package-lock.json

Backport 5493f1453627013c18e3b17c51af154bea46c5f3 from #102

[Backport stable23] Bump url-parse from 1.5.7 to 1.5.10

---

lib/BackgroundJobs/ProcessFileJob.php
lib/Operation.php
tests/Unit/BackgroundJobs/ProcessFileJobTest.php
tests/Unit/OperationTest.php
tests/psalm-baseline.xml

Backport 3b0f56a6c6d4e034a02771a539f64648aaf48b7d from #116

[Backport stable24] Use uid from filepath

---

README.md
lib/OcrProcessors/PdfOcrProcessor.php
src/components/WorkflowOcr.vue
src/test/components/WorkflowOcr.spec.js

Add chinese simplified

---

README.md
lib/OcrProcessors/PdfOcrProcessor.php
src/components/WorkflowOcr.vue
src/test/components/WorkflowOcr.spec.js

Backport 2469940df1a93cf4f9205136babdef4b8196f27f from #120

[Backport stable24] Add chinese simplified

---

.github/workflows/codecov.yml
.github/workflows/phpunit.yml
README.md
composer.json
composer.lock
lib/AppInfo/Application.php
lib/BackgroundJobs/ProcessFileJob.php
lib/OcrProcessors/IOcrProcessor.php
lib/OcrProcessors/IOcrProcessorFactory.php
lib/OcrProcessors/ImageOcrProcessor.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
lib/OcrProcessors/OcrProcessorFactory.php
lib/OcrProcessors/OcrProcessorResult.php
lib/Operation.php
lib/Service/IOcrService.php
lib/Service/OcrService.php
psalm.xml
tests/Unit/BackgroundJobs/ProcessFileJobTest.php
tests/Unit/OcrProcessors/ImageOcrProcessorTest.php
tests/Unit/OcrProcessors/OcrProcessorFactoryTest.php
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
tests/Unit/Service/OcrServiceTest.php
tests/psalm-baseline.xml

Backport 5efcfebeffde2136fa1f7768ba31240a535b9ec8 from #111

[Backport stable24] Add image conversion

---

.github/workflows/codecov.yml
.github/workflows/phpunit.yml
README.md
lib/AppInfo/Application.php
lib/BackgroundJobs/ProcessFileJob.php
lib/OcrProcessors/IOcrProcessor.php
lib/OcrProcessors/IOcrProcessorFactory.php
lib/OcrProcessors/ImageOcrProcessor.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
lib/OcrProcessors/OcrProcessorFactory.php
lib/OcrProcessors/OcrProcessorResult.php
lib/Operation.php
lib/Service/IOcrService.php
lib/Service/OcrService.php
tests/Unit/BackgroundJobs/ProcessFileJobTest.php
tests/Unit/OcrProcessors/ImageOcrProcessorTest.php
tests/Unit/OcrProcessors/OcrProcessorFactoryTest.php
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
tests/Unit/Service/OcrServiceTest.php

Backport https://github.com/R0Wi/workflow_ocr/commit/5efcfebeffde2136fa1f7768ba31240a535b9ec8 from https://github.com/R0Wi/workflow_ocr/pull/111

[Backport stable23] Add image conversion

---

README.md
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php

Backport e90c57a676bb96ea38830eb14ab56f0149e750e2 from #126

[Backport stable24] Implement --skip-text as default setting

---

lib/OcrProcessors/ImageOcrProcessor.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
tests/Unit/OcrProcessors/ImageOcrProcessorTest.php

Fix dpi param

---

lib/OcrProcessors/ImageOcrProcessor.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
tests/Unit/OcrProcessors/ImageOcrProcessorTest.php

Backport 8320ae0941c80b0ae6f4502810200a2e5097ad13 from #132

[Backport stable23] Fix dpi param

---

lib/OcrProcessors/ImageOcrProcessor.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
tests/Unit/OcrProcessors/ImageOcrProcessorTest.php

Backport 8320ae0941c80b0ae6f4502810200a2e5097ad13 from #132

[Backport stable24] Fix dpi param

---

lib/OcrProcessors/OcrMyPdfBasedProcessor.php
src/components/WorkflowOcr.vue
src/test/components/WorkflowOcr.spec.js

* see also https://github.com/R0Wi/workflow_ocr/discussions/135

Add Estonian

---

lib/OcrProcessors/OcrMyPdfBasedProcessor.php
src/components/WorkflowOcr.vue
src/test/components/WorkflowOcr.spec.js

Backport 48ce85d312963369cc03b521d9efdcc5f41788ae from #136

[Backport stable23] Add Estonian

---

lib/OcrProcessors/OcrMyPdfBasedProcessor.php
src/components/WorkflowOcr.vue
src/test/components/WorkflowOcr.spec.js

Backport 48ce85d312963369cc03b521d9efdcc5f41788ae from #136

[Backport stable24] Add Estonian

---

.github/workflows/phpunit.yml
.vscode/launch.json
Makefile
jest.config.js
lib/Model/WorkflowSettings.php
lib/Service/OcrService.php
package-lock.json
package.json
src/components/GlobalSettings.vue
src/components/SettingsItem.vue
src/components/WorkflowOcr.vue
src/test/components/SettingsItem.spec.js
src/test/components/WorkflowOcr.spec.js
src/test/setup-jest.js
tests/Unit/Service/OcrServiceTest.php
webpack.js

Backport 212a19b978ad5abcf8389e851692eff14c33c93a from #143

[Backport stable24] Implement feature #88

---

.github/workflows/build.yml
.github/workflows/build_release.yml
.github/workflows/codecov.yml
.github/workflows/lint-fix.yml
.github/workflows/lint.yml
.github/workflows/phpunit.yml

Backport 8cf95ef8516c2916df3ff023da9df61c92f33ae2 from #155

[Backport stable25] [DEVOPS] Update checkout action to v3

---

.github/workflows/build.yml
.github/workflows/build_release.yml
.github/workflows/codecov.yml
.github/workflows/lint-fix.yml
.github/workflows/lint.yml
.github/workflows/phpunit.yml

Backport https://github.com/R0Wi/workflow_ocr/commit/8cf95ef8516c2916df3ff023da9df61c92f33ae2 from https://github.com/R0Wi/workflow_ocr/pull/155

[Backport stable24] [DEVOPS] Update checkout action to v3 (#155)

---

lib/BackgroundJobs/ProcessFileJob.php
tests/Unit/BackgroundJobs/ProcessFileJobTest.php

Backport 8cfba2c7463f54e45aa35bab0441cba56b8e84c0 from #160

[Backport stable25] Implement #130

---

jest.config.js
lib/Model/WorkflowSettings.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
src/components/WorkflowOcr.vue
src/test/OC.js
src/test/components/WorkflowOcr.spec.js
src/test/setup-jest.js
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php

Backport ab2cdadf02a3aa1114eb1c9aff93c8c8619613df from #177

[Backport stable25] Implement 'skip file' option (default for ocrmypdf) implements #173

---

lib/Controller/OcrBackendInfoController.php

Backport 46d9ed8e011a7b522bef9c1b6ec08860607da244 from #186

[Backport stable24] Make installed langs available for non-admin users (fix #184)

---

lib/Controller/OcrBackendInfoController.php

Backport 46d9ed8e011a7b522bef9c1b6ec08860607da244 from #186

[Backport stable25] Make installed langs available for non-admin users (fix #184)

---

.gitignore
appinfo/info.xml

Reported-by: @CaféTango
Signed-off-by: Jérémie Tarot (@silopolis) <silopolis@gmail.com>

strings: fix app summary spelling

---

composer.json
composer.lock
composer/autoload.php
lib/AppInfo/Application.php
tests/Integration/AppTest.php
tests/Unit/composer/autoloadTest.php

Backport 97f33cc6aa8ceaf57d58ec72e4fa62255e127105 from #199

[Backport stable26] Use PSR-4 autoloader

---

package-lock.json

Backport 13af13c692d2d332c8396938606369abf0bace45 from #208

[Backport stable26] Bump tough-cookie from 4.1.2 to 4.1.3

---

composer.json
tests/Integration/Composer/AutoloaderTest.php

* See also https://github.com/nextcloud/calendar/pull/5295

fix: Allow dynamic autoloading for classes added during upgrade

---

lib/BackgroundJobs/ProcessFileJob.php
lib/Exception/OcrResultEmptyException.php
lib/Migration/Version2404Date20220903071748.php
lib/OcrProcessors/OcrMyPdfBasedProcessor.php
lib/Service/IOcrService.php
lib/Service/OcrService.php
tests/Integration/Notification/NotificationTest.php
tests/Unit/BackgroundJobs/ProcessFileJobTest.php
tests/Unit/OcrProcessors/PdfOcrProcessorTest.php
tests/Unit/Service/OcrServiceTest.php
tests/psalm-baseline.xml

Backport a01163c0e098cd09ee50872f1cdc6b7e2fe54e7e from #233

[Backport stable27] Skip notifications when OCR mode is "skip file"

---

composer.lock
lib/BackgroundJobs/ProcessFileJob.php
lib/Model/WorkflowSettings.php
lib/Service/INotificationService.php
lib/Service/NotificationService.php
lib/Wrapper/ViewWrapper.php

* Update composer deps for NC29

NC29 fixes

---

.github/workflows/lint.yml
.github/workflows/phpunit.yml
.github/workflows/psalm.yml
appinfo/info.xml

Add PHP8.3 support to NC28 version

---

lib/Operation.php
tests/Unit/OperationTest.php

Add support for rename and copy events

---

composer.lock
lib/OcrProcessors/Remote/Client/Model/ErrorResult.php
lib/OcrProcessors/Remote/Client/openapi-spec.json
tests/psalm-baseline.xml

* See also https://github.com/R0Wi-DEV/workflow_ocr_backend/pull/2

Add ocrmypdf exit code to API result model

---

lib/OcrProcessors/Remote/Client/Model/ErrorResult.php
lib/OcrProcessors/Remote/Client/openapi-spec.json
tests/psalm-baseline.xml

Backport of https://github.com/R0Wi-DEV/workflow_ocr/pull/302

[backport stable31] Add ocrmypdf exit code to API result model

---

.github/workflows/phpunit-integration.yml
.github/workflows/phpunit.yml
.github/workflows/sonarqube.yml

* TestCase->loginAsUser depends on oc_external_mounts table
* Enable app to trigger migrations

Enable files_external to fix Integrationtests
